name: Publish
on:
  pull_request:
    branches:

      - master
  push:
    branches :
      - master

jobs:
  library:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
  apk:
    name: Build apk, upload to release and notify Discord
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Delete some caches
        run: rm -f ~/.gradle/caches/modules-2/modules-2.lock; rm -fr ~/.gradle/caches/*/plugin-resolution/
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/build-cache
            ~/.m2
            ~/.gradle
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Delete previous outputs
        run: rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
      - name: Make gradlew executable
        run: chmod +x gradlew; chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Build master app
        run: ./gradlew clean :app:assembleRelease --full-stacktrace
      - name: Upload APK to release
        id: upload_apk
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITH_TOKEN }}
          file: "./app/build/outputs/apk/release/"

          asset_name: "release.apk"
          tag: 1.0
          overwrite: true
      - name: Build Signed APK
        uses: victorbnl/build-signed-apk@main
        with:
          keystore_file: ${{ secrets.keystore }}
          keystore_password: ${{ secrets.keystore_password }}
          key_alias: ${{ secrets.key_alias }}
          key_password: ${{ secrets.key_password }}